backend:
  name: git-gateway
  branch: main

media_folder: "src/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "home"
    label: "Home"
    file: "src/index.md"
    fields:
      - { name: "title", label: "Page Title", widget: "string" }
      - { name: "welcome_heading", label: "Welcome Heading", widget: "string" }
      - { name: "intro_text", label: "Intro Text", widget: "text" }
      - label: "Section Images"
        name: "section_images"
        widget: "list"
        fields:
          - { label: "Image", name: "image", widget: "image" }
          - { label: "Caption", name: "caption", widget: "string", required: false }

  - name: "our-story"
    label: "Our Story"
    file: "src/pages/our-story.md"
    fields:
      - { name: "title", label: "Page Title", widget: "string" }
      - { name: "welcome_heading", label: "Welcome Heading", widget: "string" }
      - { name: "intro_text", label: "Intro Text", widget: "text" }

  - name: "services"
    label: "Services"
    file: "src/pages/services.md"
    fields:
      - { name: "title", label: "Page Title", widget: "string" }
      - { name: "welcome_heading", label: "Welcome Heading", widget: "string" }
      - { name: "intro_text", label: "Intro Text", widget: "text" }

  - name: "testimonials"
    label: "Testimonials"
    file: "src/pages/testimonials.md"
    fields:
      - { name: "title", label: "Page Title", widget: "string" }
      - { name: "welcome_heading", label: "Welcome Heading", widget: "string" }
      - { name: "intro_text", label: "Intro Text", widget: "text" }
      - label: "Testimonials"
        name: "testimonials"
        widget: "list"
        fields:
          - { label: "Quote", name: "quote", widget: "text" }
          - { label: "Author", name: "author", widget: "string" }

  - name: "gallery"
    label: "Gallery"
    files:
      - label: "Gallery Page"
        name: "gallery"
        file: "src/pages/gallery.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - label: "Image Groups"
            name: "groups"
            widget: "list"
            fields:
              - { label: "Group Name", name: "group_name", widget: "string" }
              - label: "Images"
                name: "images"
                widget: "list"
                fields:
                  - { label: "Image", name: "image", widget: "image" }
                  - { label: "Caption", name: "caption", widget: "string", required: false }

  - name: "contact"
    label: "Contact"
    files:
      - label: "Contact Page"
        name: "contact"
        file: "src/pages/contact.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Intro Text", name: "intro_text", widget: "markdown" }