backend:
  branch: main
  name: git-gateway
collections:
- files:
  - fields:
    - label: Title
      name: title
      widget: string
    - label: Welcome Heading
      name: welcome_heading
      widget: string
    - label: Intro Text
      name: intro_text
      widget: text
    - fields:
      - label: Image
        name: image
        widget: image
      label: Section Images
      name: section_images
      widget: list
    file: index.md
    label: Home
    name: home
  folder: ''
  label: Pages
  name: pages
media_folder: images
public_folder: /images
