backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "homepage"
    label: "Homepage"
    files:
      - file: "src/index.md"
        label: "Homepage Content"
        name: "homepage"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Layout", name: "layout", widget: "string" }
          - { label: "Permalink", name: "permalink", widget: "string" }
          - { label: "Welcome heading", name: "welcome_heading", widget: "string" }
          - { label: "Intro text", name: "intro_text", widget: "markdown" }
          - { label: "Section Images", name: "section_images", widget: "list", allow_add: true, fields: [
              { label: "Image", name: "image", widget: "image" },
              { label: "Alt text", name: "alt", widget: "string" }
            ] }

  - name: "ourstory"
    label: "Our Story"
    files:
      - file: "src/pages/our-story.md"
        label: "Our Story Content"
        name: "ourstory"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Layout", name: "layout", widget: "string" }
          - { label: "Permalink", name: "permalink", widget: "string" }
          - { label: "Welcome heading", name: "welcome_heading", widget: "string" }
          - { label: "Intro text", name: "intro_text", widget: "markdown" }

  - name: "services"
    label: "Services"
    files:
      - file: "src/pages/services.md"
        label: "Services Content"
        name: "services"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Layout", name: "layout", widget: "string" }
          - { label: "Permalink", name: "permalink", widget: "string" }
          - { label: "Welcome heading", name: "welcome_heading", widget: "string" }
          - { label: "Intro text", name: "intro_text", widget: "markdown" }

  - name: "testimonials"
    label: "Testimonials"
    files:
      - file: "src/pages/testimonials.md"
        label: "Testimonials Content"
        name: "testimonials"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Layout", name: "layout", widget: "string" }
          - { label: "Permalink", name: "permalink", widget: "string" }
          - { label: "Welcome heading", name: "welcome_heading", widget: "string" }
          - { label: "Intro text", name: "intro_text", widget: "markdown" }
          - label: "Testimonials"
            name: "testimonials"
            widget: "list"
            fields:
              - { label: "Quote", name: "quote", widget: "text" }
              - { label: "Author", name: "author", widget: "string" }
              - { label: "Location", name: "location", widget: "string" }

  - name: "contact"
    label: "Contact"
    files:
      - file: "src/pages/contact.md"
        label: "Contact Content"
        name: "contact"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Layout", name: "layout", widget: "string" }
          - { label: "Permalink", name: "permalink", widget: "string" }
          - { label: "Welcome heading", name: "welcome_heading", widget: "string" }
          - { label: "Intro text", name: "intro_text", widget: "markdown" }


  - label: "Gallery"
    name: "gallery"
    folder: "src/pages/gallery"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Welcome Heading", name: "welcome_heading", widget: "string", required: false }
      - { label: "Intro Text", name: "intro_text", widget: "markdown", required: false }
      - { label: "Permalink", name: "permalink", widget: "string", default: "gallery/index.html" }
      - { label: "Layout", name: "layout", widget: "hidden", default: "gallery" }
      - label: "Groups"
        name: "groups"
        widget: "list"
        summary: "{{fields.group_title}}"
        fields:
          - { label: "Group Title", name: "group_title", widget: "string" }
          - label: "Images"
            name: "images"
            widget: "list"
            fields:
              - { label: "Image", name: "image", widget: "image" }
              - { label: "Caption", name: "caption", widget: "string", required: false }
              - { label: "Alt Text", name: "alt", widget: "string", required: false }